name: Build and Push Docker Image with Auto Version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine next tag
        id: versioning
        run: |
          latest_tag=$(git tag | grep '^v' | sort -V | tail -n1)
          echo "Latest tag: $latest_tag"
          if [ -z "$latest_tag" ]; then
            new_tag="v1.0"
          else
            version_number=${latest_tag#v}
            major=${version_number%%.*}
            minor=${version_number#*.}
            new_minor=$((minor + 1))
            new_tag="v${major}.${new_minor}"
          fi
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: queenie324/docker_build:${{ steps.versioning.outputs.new_tag }}

      - name: Push Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.versioning.outputs.new_tag }}
          git push origin ${{ steps.versioning.outputs.new_tag }}
